### ISSUE TITLE
Color modernization

### ISSUE THREAD

**Issue by szepeviktor** [KOLANICH/dBug#10]
Please change colors to flat ones.
http://flatuicolors.com/

**Comment by KOLANICH** [comment]
What's wrong with current colour theme?
In any case anyone can edit css to change it. Also see #11.

**Comment by szepeviktor** [comment]
The current colors are *full* colors, reminding me of the CGA monitor.



-- 
+36204242498
Ezen a készüléken nehéz gépelni. 
Elnézést!

**Comment by KOLANICH** [comment]
Why do you think it is bad?

**Comment by szepeviktor** [comment]
I perceive seeing flat colors are more pleasant experience.

**Comment by szepeviktor** [comment]
Try it with dBug. It take 5 minutes to copy&paste color codes.

**Comment by KOLANICH** [comment]
Looks terrible.
