### ISSUE TITLE
off: See dBug in action

### ISSUE THREAD

**Issue by szepeviktor** [KOLANICH/dBug#3]
https://github.com/szepeviktor/option-inspector
Go to WordPress admin / Settings / Options, click on a serialized value.

**Comment by KOLANICH** [comment]
Sorry, I won't check it on WordPress because I don't use CMSes. Are there any troubles with embedding? Also, think about inheritance instead of editing the code.
1 self::initJSandCSS(); -> static::initJSandCSS();
2 you can inherit your class from mine and redefine

**Comment by szepeviktor** [comment]
Than you for the suggestion.
WordPress has a *secret* options page wich does not show serialized values. This plugin opens up a lightbox with these values.
I consider extending your class.

**Comment by szepeviktor** [comment]
Do you mean?

```php
class mine extends dBug\dBug {
  static initJSandCSS() {
  }
}
```

**Comment by szepeviktor** [comment]
> self::initJSandCSS(); -> static::initJSandCSS();

Do you mean still editing the code a bit?

**Comment by KOLANICH** [comment]
Yes. But without changing base class it won't work. [Static binding](http://php.net/manual/en/language.oop5.late-static-bindings.php) requires php 5.3, so this hasn't been done yet.

**Comment by KOLANICH** [comment]
So
1 Modify
2 test
3 send a pr

**Comment by szepeviktor** [comment]
I hold that 5.3 is ancient also. I use 5.5.
http://php.net/ shows that 5.4 is the oldest supported release.

**Comment by KOLANICH** [comment]
I saw a hosting that used php5.2 in 2010. When i asked them about update they asked if i'd pay for it.

**Comment by szepeviktor** [comment]
Yes shared hosting must stick to the initial version. In case of a PHP upgrade those *left there* websites would need a developer.
https://github.com/KOLANICH/dBug/pull/4
